const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Assessment = require('../models/Assessment');

dotenv.config();

const categories = {
  'Programming': ['Python', 'Java', 'C++', 'C#', 'Go', 'Rust', 'Ruby', 'PHP', 'Swift', 'Kotlin', 'TypeScript', 'JavaScript', 'C', 'Perl', 'Scala', 'Haskell', 'Dart', 'R', 'MATLAB', 'Shell Scripting'],
  'Web Development': ['React.js', 'Angular', 'Vue.js', 'Node.js', 'Next.js', 'Svelte', 'Express.js', 'Django', 'Flask', 'Spring Boot', 'Laravel', 'ASP.NET Core', 'Ruby on Rails', 'GraphQL', 'REST API Design', 'HTML5 & CSS3', 'Tailwind CSS', 'Bootstrap', 'WebSockets', 'PWA'],
  'Mobile Development': ['React Native', 'Flutter', 'SwiftUI', 'Android Jetpack Compose', 'Ionic', 'Xamarin', 'Mobile UI Design', 'Firebase for Mobile', 'App Store Optimization', 'Mobile Security'],
  'Data & AI': ['Machine Learning', 'Deep Learning', 'Natural Language Processing', 'Computer Vision', 'Data Analysis with Python', 'Big Data Engineering', 'SQL Mastery', 'NoSQL Databases', 'Data Visualization', 'TensorFlow', 'PyTorch', 'Apache Spark', 'Power BI', 'Tableau'],
  'Cloud & DevOps': ['AWS Cloud Practitioner', 'Azure Fundamentals', 'Google Cloud Platform', 'Docker & Containers', 'Kubernetes Orchestration', 'Terraform (IaC)', 'Jenkins CI/CD', 'GitHub Actions', 'Linux Administration', 'Serverless Computing', 'Microservices Architecture'],
  'Cybersecurity': ['Ethical Hacking', 'Network Security', 'Application Security', 'Penetration Testing', 'Cryptography', 'Cloud Security', 'Incident Response', 'Identity & Access Management', 'SIEM Operations', 'Zero Trust Architecture'],
  'Design & UX': ['UI Design Principles', 'UX Research', 'Figma Mastery', 'Adobe Creative Suite', 'Design Systems', 'Responsive Design', 'Interaction Design', 'Prototyping', 'Visual Branding', 'Typography for Web'],
  'Professional & Management': ['Project Management', 'Agile & Scrum', 'Product Management', 'Digital Marketing', 'Business Analytics', 'Technical Writing', 'Public Speaking', 'Leadership Skills', 'Customer Success', 'HR Management']
};

const specialAssessments = {
  'React.js': {
    title: 'React.js Professional Certification',
    description: 'The industry-standard certification for React.js developers. This comprehensive assessment evaluates your mastery of modern React patterns, performance optimization, state management, and ecosystem integration. Required for high-tier React project bids.',
    difficulty: 'Senior',
    reward: 'Elite React Badge',
    questions: [
      {
        question: "What is the primary purpose of the 'Virtual DOM' in React?",
        type: 'mcq',
        options: [
          { text: 'To provide a direct mapping to the browser DOM for faster manipulation.', isCorrect: false },
          { text: 'To minimize expensive DOM operations by batching updates and performing efficient diffing.', isCorrect: true },
          { text: 'To allow React to run on the server without any browser environment.', isCorrect: false },
          { text: 'To serve as a storage for global application state.', isCorrect: false }
        ],
        points: 2
      },
      {
        question: "Which hook should be used to perform a side effect only once after the initial component mounting?",
        type: 'mcq',
        options: [
          { text: 'useEffect(() => { ... }, [state])', isCorrect: false },
          { text: 'useEffect(() => { ... }, [])', isCorrect: true },
          { text: 'useMemo(() => { ... }, [])', isCorrect: false },
          { text: 'useLayoutEffect(() => { ... })', isCorrect: false }
        ],
        points: 2
      },
      {
        question: "What is 'Reconciliation' in React?",
        type: 'mcq',
        options: [
          { text: 'The process of translating JSX into executable JavaScript.', isCorrect: false },
          { text: 'The algorithm React uses to diff one tree with another to determine which parts need to be changed.', isCorrect: true },
          { text: 'The process of synchronizing props between parent and child components.', isCorrect: false },
          { text: 'The method used to merge multiple state updates into a single re-render.', isCorrect: false }
        ],
        points: 3
      },
      {
        question: "When using 'useMemo', what is being memoized?",
        type: 'mcq',
        options: [
          { text: 'The function definition itself.', isCorrect: false },
          { text: 'The result of a function execution.', isCorrect: true },
          { text: 'The component instance.', isCorrect: false },
          { text: 'The DOM nodes generated by the component.', isCorrect: false }
        ],
        points: 2
      },
      {
        question: "What is the correct way to update state based on the previous state value?",
        type: 'mcq',
        options: [
          { text: 'setState(state + 1)', isCorrect: false },
          { text: 'setState(prevState => prevState + 1)', isCorrect: true },
          { text: 'state = state + 1', isCorrect: false },
          { text: 'setState({ count: state.count + 1 })', isCorrect: false }
        ],
        points: 2
      },
      {
        question: "What is the benefit of 'React.memo'?",
        type: 'mcq',
        options: [
          { text: 'It automatically caches all API requests made by the component.', isCorrect: false },
          { text: 'It prevents a functional component from re-rendering if its props haven\'t changed.', isCorrect: true },
          { text: 'It speeds up the mounting process of heavy components.', isCorrect: false },
          { text: 'It reduces the memory footprint of the application.', isCorrect: false }
        ],
        points: 3
      },
      {
        question: "In React 18, what does 'Concurrent Mode' (Transitions) primarily help with?",
        type: 'mcq',
        options: [
          { text: 'Running multiple React apps on the same page.', isCorrect: false },
          { text: 'Keeping the UI responsive during heavy non-urgent updates.', isCorrect: true },
          { text: 'Automatically parallelizing network requests.', isCorrect: false },
          { text: 'Improving the SEO of the application.', isCorrect: false }
        ],
        points: 4
      },
      {
        question: "Which of the following is true about React Portals?",
        type: 'mcq',
        options: [
          { text: 'They are used to share state between different React trees.', isCorrect: false },
          { text: 'They allow rendering a child component into a DOM node that exists outside the DOM hierarchy of the parent component.', isCorrect: true },
          { text: 'They are a replacement for the Context API.', isCorrect: false },
          { text: 'They automatically handle z-index issues for all modals.', isCorrect: false }
        ],
        points: 3
      },
      {
        question: "What is the 'Hydration' process in the context of Next.js or SSR?",
        type: 'mcq',
        options: [
          { text: 'Clearing the cache after a new deployment.', isCorrect: false },
          { text: 'The process of attaching event listeners to the HTML sent from the server to make it interactive.', isCorrect: true },
          { text: 'Compressing JavaScript bundles for faster download.', isCorrect: false },
          { text: 'Fetching data from the client-side after the server has rendered.', isCorrect: false }
        ],
        points: 4
      },
      {
        question: "How does 'useRef' differ from 'useState'?",
        type: 'mcq',
        options: [
          { text: 'useRef can only store DOM elements.', isCorrect: false },
          { text: 'Updating a ref does not trigger a component re-render.', isCorrect: true },
          { text: 'useRef values are lost on every render.', isCorrect: false },
          { text: 'useState is async, while useRef is sync.', isCorrect: false }
        ],
        points: 2
      },
      {
        question: "What is an Error Boundary in React?",
        type: 'mcq',
        options: [
          { text: 'A try-catch block inside a functional component.', isCorrect: false },
          { text: 'A class component that catches JavaScript errors anywhere in its child component tree.', isCorrect: true },
          { text: 'A tool for debugging network errors in the browser.', isCorrect: false },
          { text: 'A prop used to validate data types.', isCorrect: false }
        ],
        points: 3
      },
      {
        question: "What is the main advantage of 'Server Components' in React?",
        type: 'mcq',
        options: [
          { text: 'They make the frontend code run faster on mobile devices.', isCorrect: false },
          { text: 'They reduce the amount of JavaScript sent to the client by rendering on the server.', isCorrect: true },
          { text: 'They allow the use of hooks like useState on the server.', isCorrect: false },
          { text: 'They replace the need for an API backend.', isCorrect: false }
        ],
        points: 5
      },
      {
        question: "Technical Challenge: Implement a useLocalStorage hook",
        type: 'coding',
        language: 'nodejs20',
        initialCode: `// Implement a useLocalStorage hook\n// It should take a key and an initialValue\n// It should return [storedValue, setValue]\n// The value should persist in window.localStorage\n\nfunction useLocalStorage(key, initialValue) {\n  // Your code here\n}`,
        testCases: [{ input: 'testKey, testValue', output: 'testValue', isPublic: true }],
        points: 10
      },
      {
        question: "Technical Challenge: Build a FileTree component",
        type: 'coding',
        language: 'nodejs20',
        initialCode: `// Build a FileTree component that renders a nested structure\n// Example data: [{ name: 'folder', children: [{ name: 'file.txt' }] }]\n\nfunction FileTree({ data }) {\n  // Your code here\n}`,
        testCases: [{ input: 'nested_data', output: 'rendered_html', isPublic: true }],
        points: 15
      }
    ]
  }
};

const generateAssessments = () => {
  const allAssessments = [];
  let skillCount = 0;

  for (const [category, skills] of Object.entries(categories)) {
    for (const skill of skills) {
      skillCount++;
      const testId = `${skill.replace(/[^a-zA-Z0-9]/g, '').toUpperCase()}-INT-${skillCount.toString().padStart(3, '0')}`;
      
      const assessment = {
        testId,
        title: `${skill} (Intermediate)`,
        description: `Advanced validation of ${skill} expertise. This assessment evaluates practical knowledge, architectural patterns, and troubleshooting capabilities in ${category}.`,
        duration: 90,
        difficulty: 'Intermediate',
        reward: `${skill} Verified Badge`,
        category: category,
        cutoffScore: 90,
        isProctored: true,
        questions: []
      };

      // Check for specialized assessment content
      if (specialAssessments[skill]) {
        const special = specialAssessments[skill];
        assessment.title = special.title;
        assessment.description = special.description;
        assessment.difficulty = special.difficulty;
        assessment.reward = special.reward;
        assessment.questions = special.questions;
        allAssessments.push(assessment);
        continue;
      }

      // Skill-specific templates for better quality
      const getSkillSpecificTemplates = (skillName) => {
        const lowerSkill = skillName.toLowerCase();
        if (lowerSkill.includes('react')) {
          return [
            `What is the primary purpose of the Virtual DOM in ${skillName}?`,
            `How does ${skillName} handle prop drilling in large-scale applications?`,
            `What are the advantages of using Functional Components over Class Components in ${skillName}?`,
            `Explain the reconciliation process in ${skillName}.`,
            `How do you optimize performance for a large list in ${skillName}?`
          ];
        }
        if (lowerSkill.includes('python')) {
          return [
            `What is the difference between a list and a tuple in ${skillName}?`,
            `How does ${skillName} handle memory management and garbage collection?`,
            `What is a decorator in ${skillName} and when should you use it?`,
            `Explain the difference between 'is' and '==' in ${skillName}.`,
            `What are generators in ${skillName} and how do they differ from iterators?`
          ];
        }
        return [];
      };

      const skillTemplates = getSkillSpecificTemplates(skill);
      const questionTemplates = [
        ...skillTemplates,
        `What is the primary architectural benefit of using ${skill} in a production-scale system?`,
        `When debugging a high-latency issue in a ${skill} environment, which tool/pattern is most effective?`,
        `How does ${skill} handle internal state management compared to industry alternatives?`,
        `Which of the following is a security best practice specifically for ${skill} implementations?`,
        `In a microservices architecture, how should ${skill} components ideally communicate?`,
        `What is the time complexity of the core data structure used by ${skill} for lookup operations?`,
        `How do you implement effective error boundary patterns within a ${skill} application?`,
        `What is the recommended strategy for horizontal scaling of ${skill} instances?`,
        `Which design pattern is most commonly used in ${skill} to decouple business logic?`,
        `How does ${skill} ensure data consistency during concurrent write operations?`
      ];

      // Options templates to provide variety
      const optionsTemplates = [
        [
          `Optimized ${skill} performance and maintainability`,
          `Legacy compatibility with non-${skill} systems`,
          `Reducing development time at the cost of scalability`,
          `Minimal configuration overhead for small teams`
        ],
        [
          `High-fidelity ${skill} reactive state management`,
          `Direct memory access without abstraction layers`,
          `Compiled-time optimization for low-end hardware`,
          `Native support for legacy ${skill} plugins`
        ],
        [
          `Distributed architecture with ${skill} micro-kernels`,
          `Monolithic deployment for simplified orchestration`,
          `Event-driven synchronization between ${skill} nodes`,
          `Stateless execution within a virtualized sandbox`
        ],
        [
          `Strict type safety and compile-time validation`,
          `Dynamic interpretation for rapid prototyping`,
          `Garbage-collected memory with deterministic cleanup`,
          `Just-in-time compilation for adaptive performance`
        ]
      ];

      // Generate 20 MCQs
      for (let i = 0; i < 20; i++) {
        const template = questionTemplates[i % questionTemplates.length];
        const optionsRaw = optionsTemplates[i % optionsTemplates.length];
        const correctIdx = Math.floor(Math.random() * 4);
        
        const options = optionsRaw.map((optText, idx) => ({
          text: optText,
          isCorrect: idx === correctIdx
        }));
        
        assessment.questions.push({
          id: i + 1,
          question: template,
          type: 'mcq',
          options: options,
          points: 1
        });
      }

      // Add 3 Coding Challenges
      const isCoding = ['Programming', 'Web Development', 'Mobile Development', 'Data & AI'].includes(category);
      const language = isCoding ? (skill.toLowerCase().includes('python') ? 'python' : 'nodejs20') : 'text';

      const codingChallenges = [
        `Implement a ${skill} utility function that handles asynchronous retry logic with exponential backoff.`,
        `Refactor the following ${skill} code snippet to improve its time complexity from O(n^2) to O(n log n).`,
        `Create a robust validation schema for a ${skill} data model ensuring strict type integrity.`
      ];

      for (let j = 0; j < 3; j++) {
        assessment.questions.push({
          question: `Technical Challenge ${j + 1}: ${isCoding ? 'Implement' : 'Describe'} ${codingChallenges[j]}`,
          type: 'coding',
          language: language,
          initialCode: language === 'python' ? `# Python Solution\ndef solution():\n    # Your code for ${skill} here\n    pass` : language === 'nodejs20' ? `// Node.js Solution\nfunction solution() {\n    // Your code for ${skill} here\n}` : `// Provide your detailed response regarding ${skill} here`,
          testCases: [{ input: 'test_input', output: 'expected_output', isPublic: true }],
          points: 10
        });
      }

      allAssessments.push(assessment);
    }
  }

  return allAssessments;
};


const seedDB = async () => {
  try {
    const mongoUri = process.env.MONGO_URI || 'mongodb://localhost:27017/skillscrumpt';
    await mongoose.connect(mongoUri);
    console.log('Connected to MongoDB');

    // Clear all existing assessments to start fresh with the 100+ list
    await Assessment.deleteMany({});
    console.log('Cleared all existing assessments');

    const assessments = generateAssessments();
    await Assessment.insertMany(assessments);
    console.log(`${assessments.length} assessments seeded successfully with unique IDs!`);

    process.exit();
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
};

seedDB();
